import {
  Franchise,
  ProductMasterItem,
  Lead,
  Opportunity,
  Quotation,
  SalesOrder,
  Installation,
  SupportTicket,
  Renewal,
  CommissionRecord,
  CustomerProfile,
  TerritoryMapping,
  UserSession,
} from "./types";

export const MOCK_USERS: UserSession[] = [
  {
    id: "usr-ho-1",
    name: "Vikram Rathore",
    email: "vikram.ho@arguscnc.com",
    role: "head_office_admin",
    franchiseId: null,
    avatar: "VR",
  },
  {
    id: "usr-cbe-admin",
    name: "Sundaramurthy K",
    email: "admin.cbe@arguscnc.com",
    role: "franchise_admin",
    franchiseId: "FR-CBE",
    franchiseName: "Coimbatore Franchise",
    avatar: "SK",
  },
  {
    id: "usr-cbe-sales",
    name: "Karthik M",
    email: "karthik.sales@arguscnc.com",
    role: "franchise_sales",
    franchiseId: "FR-CBE",
    franchiseName: "Coimbatore Franchise",
    avatar: "KM",
  },
  {
    id: "usr-cbe-eng",
    name: "Ramesh Kumar",
    email: "ramesh.service@arguscnc.com",
    role: "service_engineer",
    franchiseId: "FR-CBE",
    franchiseName: "Coimbatore Franchise",
    avatar: "RK",
  },
  {
    id: "usr-ho-fin",
    name: "Priya Sharma",
    email: "priya.finance@arguscnc.com",
    role: "finance_accounts",
    franchiseId: null,
    avatar: "PS",
  },
  {
    id: "usr-che-admin",
    name: "Balaji Natarajan",
    email: "admin.chennai@arguscnc.com",
    role: "franchise_admin",
    franchiseId: "FR-CHE",
    franchiseName: "Chennai Franchise",
    avatar: "BN",
  },
];

export const MOCK_FRANCHISES: Franchise[] = [
  {
    _id: "fr-1",
    code: "FR-CBE",
    name: "Coimbatore Franchise",
    location: "Coimbatore, Tamil Nadu",
    state: "Tamil Nadu",
    territoryDistricts: ["Coimbatore", "Tiruppur", "Erode", "Nilgiris"],
    pincodes: ["641001", "641002", "641004", "641014", "641035", "641601"],
    agreementStartDate: "2023-01-01",
    agreementEndDate: "2026-12-31",
    status: "Active",
    annualTarget: 15000000, // ₹1.5 Cr
    achievedSales: 11420000, // ₹1.14 Cr
    collections: 9800000,
    commissionEarned: 913600,
    commissionPaid: 840000,
    contactPerson: "Sundaramurthy K",
    email: "admin.cbe@arguscnc.com",
    phone: "+91 98421 00211",
  },
  {
    _id: "fr-2",
    code: "FR-CHE",
    name: "Chennai Franchise",
    location: "Chennai, Tamil Nadu",
    state: "Tamil Nadu",
    territoryDistricts: ["Chennai", "Kanchipuram", "Chengalpattu", "Thiruvallur"],
    pincodes: ["600001", "600028", "600032", "600058", "600096"],
    agreementStartDate: "2022-06-01",
    agreementEndDate: "2025-05-31",
    status: "Active",
    annualTarget: 18000000,
    achievedSales: 13800000,
    collections: 12200000,
    commissionEarned: 1104000,
    commissionPaid: 1050000,
    contactPerson: "Balaji Natarajan",
    email: "admin.chennai@arguscnc.com",
    phone: "+91 98400 44512",
  },
  {
    _id: "fr-3",
    code: "FR-BLR",
    name: "Bangalore Franchise",
    location: "Bangalore, Karnataka",
    state: "Karnataka",
    territoryDistricts: ["Bangalore Urban", "Bangalore Rural", "Ramnagar"],
    pincodes: ["560001", "560058", "560068", "560100"],
    agreementStartDate: "2023-03-15",
    agreementEndDate: "2026-03-14",
    status: "Active",
    annualTarget: 16000000,
    achievedSales: 10400000,
    collections: 9100000,
    commissionEarned: 832000,
    commissionPaid: 750000,
    contactPerson: "Girish Gowda",
    email: "admin.blr@arguscnc.com",
    phone: "+91 98450 11984",
  },
  {
    _id: "fr-4",
    code: "FR-MDU",
    name: "Madurai Franchise",
    location: "Madurai, Tamil Nadu",
    state: "Tamil Nadu",
    territoryDistricts: ["Madurai", "Dindigul", "Theni", "Virudhunagar"],
    pincodes: ["625001", "625020"],
    agreementStartDate: "2023-08-01",
    agreementEndDate: "2026-07-31",
    status: "Active",
    annualTarget: 9000000,
    achievedSales: 6800000,
    collections: 5900000,
    commissionEarned: 544000,
    commissionPaid: 480000,
    contactPerson: "Murugesan P",
    email: "admin.mdu@arguscnc.com",
    phone: "+91 97890 22345",
  },
  {
    _id: "fr-5",
    code: "FR-SLM",
    name: "Salem Franchise",
    location: "Salem, Tamil Nadu",
    state: "Tamil Nadu",
    territoryDistricts: ["Salem", "Namakkal", "Dharmapuri"],
    pincodes: ["636001", "636004"],
    agreementStartDate: "2024-01-01",
    agreementEndDate: "2027-12-31",
    status: "Active",
    annualTarget: 8000000,
    achievedSales: 5500000,
    collections: 4800000,
    commissionEarned: 440000,
    commissionPaid: 400000,
    contactPerson: "Kandasamy V",
    email: "admin.slm@arguscnc.com",
    phone: "+91 94432 87654",
  },
];

export const MOCK_PRODUCTS: ProductMasterItem[] = [
  {
    _id: "prd-1",
    sku: "ARG-VMC-700",
    name: "ARGUS VMC-700 3-Axis Vertical Machining Center",
    category: "CNC Machines",
    listPrice: 1850000,
    franchisePurchasePrice: 1480000,
    minSellingPrice: 1650000,
    maxDiscountPercent: 10,
    gstPercent: 18,
    installationCharge: 45000,
    warrantyPeriodMonths: 12,
    renewalAmcRules: "Standard 1-year AMC @ 5% of machine invoice post warranty",
    description: "High precision 8000 RPM BT40 spindle, 700x450mm travel, Siemens 828D CNC control.",
    inStock: true,
  },
  {
    _id: "prd-2",
    sku: "ARG-CL-200",
    name: "ARGUS CNC Lathe CL-200 Slant Bed",
    category: "CNC Machines",
    listPrice: 1250000,
    franchisePurchasePrice: 1000000,
    minSellingPrice: 1125000,
    maxDiscountPercent: 10,
    gstPercent: 18,
    installationCharge: 35000,
    warrantyPeriodMonths: 12,
    renewalAmcRules: "Standard 1-year AMC @ 6% of invoice value",
    description: "Rigid 8-station hydraulic turret, max turning diameter 250mm, Fanuc 0i-TF control.",
    inStock: true,
  },
  {
    _id: "prd-3",
    sku: "ARG-ACC-4AXIS",
    name: "4th Axis Rotary Table (200mm Dia) with Tailstock",
    category: "CNC Accessories",
    listPrice: 280000,
    franchisePurchasePrice: 220000,
    minSellingPrice: 250000,
    maxDiscountPercent: 10,
    gstPercent: 18,
    installationCharge: 10000,
    warrantyPeriodMonths: 12,
    renewalAmcRules: "Bundled with VMC AMC",
    description: "Precision harmonic drive rotary indexing table for 4-axis simultaneous milling.",
    inStock: true,
  },
  {
    _id: "prd-4",
    sku: "ARG-SOFT-CAMPRO",
    name: "ArgusCAM Pro Multi-Axis CAM Software Suite",
    category: "Software",
    listPrice: 150000,
    franchisePurchasePrice: 105000,
    minSellingPrice: 135000,
    maxDiscountPercent: 10,
    gstPercent: 18,
    installationCharge: 5000,
    warrantyPeriodMonths: 12,
    renewalAmcRules: "Annual Software Maintenance & Updates @ ₹25,000/year",
    description: "Complete CAD/CAM suite with post-processors tailored for ARGUS CNC machines.",
    inStock: true,
  },
  {
    _id: "prd-5",
    sku: "ARG-AMC-VMC-ANNUAL",
    name: "Comprehensive Annual Maintenance Contract (VMC-700)",
    category: "AMC / Service",
    listPrice: 72000,
    franchisePurchasePrice: 50000,
    minSellingPrice: 65000,
    maxDiscountPercent: 10,
    gstPercent: 18,
    installationCharge: 0,
    warrantyPeriodMonths: 12,
    renewalAmcRules: "Includes 4 preventive maintenance visits + breakdown support within 24h SLA",
    description: "Preventive maintenance, spindle runout calibration, ball screw backlash check.",
    inStock: true,
  },
];

export const MOCK_CUSTOMERS: CustomerProfile[] = [
  {
    _id: "cust-1",
    customerId: "CUST-5001",
    companyName: "Sri Venkatesh Industries",
    contactPerson: "Mr. M. Karthik",
    designation: "Managing Director",
    email: "karthik@srivenkateshind.com",
    phone: "+91 98765 43210",
    industry: "Auto Components",
    address: "SF No. 44/2, SIDCO Industrial Estate, Kurichi",
    district: "Coimbatore",
    state: "Tamil Nadu",
    pincode: "641021",
    gstin: "33AAAAA0000A1Z5",
    franchiseId: "FR-CBE",
    franchiseName: "Coimbatore Franchise",
    lifetimeValue: 1945000,
    activeMachinesCount: 3,
    pendingTicketsCount: 1,
    nextRenewalDate: "2025-01-15",
    notes: "Key Tier-2 automotive precision machining vendor. High potential for 4th-axis upsell.",
  },
  {
    _id: "cust-2",
    customerId: "CUST-5002",
    companyName: "Kavitha Precision Engineering",
    contactPerson: "Mr. R. Kavitha Kumar",
    designation: "Plant Head",
    email: "kavitha@precisionengg.in",
    phone: "+91 98422 11987",
    industry: "Tool & Die",
    address: "Plot 12, Industrial Area, Peelamedu",
    district: "Coimbatore",
    state: "Tamil Nadu",
    pincode: "641004",
    gstin: "33BBBBB1111B1Z2",
    franchiseId: "FR-CBE",
    franchiseName: "Coimbatore Franchise",
    lifetimeValue: 1250000,
    activeMachinesCount: 2,
    pendingTicketsCount: 0,
    nextRenewalDate: "2025-03-10",
    notes: "Specializes in injection molds and die casting dies.",
  },
  {
    _id: "cust-3",
    customerId: "CUST-5003",
    companyName: "Precision Aero Components Pvt Ltd",
    contactPerson: "Ms. Deepa Sundar",
    designation: "VP Procurement",
    email: "deepa@aero-prec.com",
    phone: "+91 98401 22334",
    industry: "Aerospace",
    address: "SIPCOT Industrial Complex, Guindy",
    district: "Chennai",
    state: "Tamil Nadu",
    pincode: "600032",
    gstin: "33CCCCC2222C1Z9",
    franchiseId: "FR-CHE",
    franchiseName: "Chennai Franchise",
    lifetimeValue: 3100000,
    activeMachinesCount: 4,
    pendingTicketsCount: 0,
    nextRenewalDate: "2025-02-28",
    notes: "AS9100 certified aerospace machining partner.",
  },
];

export const MOCK_LEADS: Lead[] = [
  {
    _id: "lead-1",
    leadId: "LD-1041",
    customerName: "Senthil Nathan",
    companyName: "Apex Tooling Solutions",
    phone: "+91 98433 87123",
    email: "senthil@apextooling.in",
    source: "Exhibition",
    industry: "Tool & Die",
    state: "Tamil Nadu",
    district: "Coimbatore",
    pincode: "641018",
    productInterest: "ARG-VMC-700",
    ownerId: "usr-cbe-sales",
    ownerName: "Karthik M",
    franchiseId: "FR-CBE",
    franchiseName: "Coimbatore Franchise",
    status: "Qualified",
    nextFollowUpDate: "2024-12-18",
    createdAt: "2024-12-05",
    notes: "Met at INTEC 2024. Wants spindle speed > 10,000 RPM for aluminum die machining.",
  },
  {
    _id: "lead-2",
    leadId: "LD-1042",
    customerName: "Mr. M. Karthik",
    companyName: "Sri Venkatesh Industries",
    phone: "+91 98765 43210",
    email: "karthik@srivenkateshind.com",
    source: "Referral",
    industry: "Auto Components",
    state: "Tamil Nadu",
    district: "Coimbatore",
    pincode: "641021",
    productInterest: "ARG-VMC-700",
    ownerId: "usr-cbe-sales",
    ownerName: "Karthik M",
    franchiseId: "FR-CBE",
    franchiseName: "Coimbatore Franchise",
    status: "Converted",
    nextFollowUpDate: "2024-12-15",
    createdAt: "2024-11-20",
    notes: "Existing client looking to expand shop floor with additional VMC unit.",
  },
  {
    _id: "lead-3",
    leadId: "LD-1043",
    customerName: "G. Rajesh",
    companyName: "Rajesh Hi-Tech Valves",
    phone: "+91 97899 44321",
    email: "rajesh@hitechvalves.com",
    source: "Website",
    industry: "General Engg",
    state: "Tamil Nadu",
    district: "Tiruppur",
    pincode: "641601",
    productInterest: "ARG-CL-200",
    ownerId: "usr-cbe-sales",
    ownerName: "Karthik M",
    franchiseId: "FR-CBE",
    franchiseName: "Coimbatore Franchise",
    status: "New",
    nextFollowUpDate: "2024-12-20",
    territoryConflict: true,
    conflictNotes: "PIN 641601 near boundary with Salem Franchise territory. Requires HO verification.",
    createdAt: "2024-12-10",
    notes: "Needs CNC lathe for stainless steel valve bodies.",
  },
  {
    _id: "lead-4",
    leadId: "LD-1044",
    customerName: "Sundar Rajan",
    companyName: "Southern CNC Profiles",
    phone: "+91 94440 55112",
    email: "sundar@southerncnc.in",
    source: "Direct Call",
    industry: "Auto Components",
    state: "Tamil Nadu",
    district: "Chennai",
    pincode: "600058",
    productInterest: "ARG-VMC-700",
    ownerId: "usr-che-admin",
    ownerName: "Balaji Natarajan",
    franchiseId: "FR-CHE",
    franchiseName: "Chennai Franchise",
    status: "In Progress",
    nextFollowUpDate: "2024-12-19",
    createdAt: "2024-12-02",
    notes: "Requires turnkey demo on EN-8 steel sample parts.",
  },
];

export const MOCK_OPPORTUNITIES: Opportunity[] = [
  {
    _id: "op-1",
    opportunityId: "OP-1023",
    leadId: "lead-2",
    customerId: "cust-1",
    customerName: "Mr. M. Karthik",
    companyName: "Sri Venkatesh Industries",
    phone: "+91 98765 43210",
    email: "karthik@srivenkateshind.com",
    franchiseId: "FR-CBE",
    franchiseName: "Coimbatore Franchise",
    stage: "Demo",
    expectedValue: 1840000,
    product: "ARG-VMC-700 3-Axis Vertical Machining Center",
    requirementsNotes: "Customer requested 3 sample trial components in EN-19 steel. Spindle vibration analysis required.",
    demo: {
      demoId: "DEMO-801",
      scheduledDate: "2024-12-11",
      conductedDate: "2024-12-11",
      assignedEngineerId: "usr-cbe-eng",
      assignedEngineerName: "Ramesh Kumar",
      product: "ARG-VMC-700",
      status: "Completed",
      result: "Positive",
      notes: "Trial cycle time achieved: 4m 12s vs 5m customer target. Customer satisfied with surface finish (Ra 0.8).",
      attachments: ["component_drawings.pdf", "cycle_time_report.xlsx"],
    },
    timeline: [
      { stage: "New Lead", date: "20 Nov 2024", completed: true, note: "Lead received via Referral" },
      { stage: "Qualified", date: "25 Nov 2024", completed: true, note: "Budget & technical fit verified" },
      { stage: "Demo Conducted", date: "11 Dec 2024", completed: true, note: "Positive result on EN-19 test part" },
      { stage: "Quotation Sent", date: "12 Dec 2024", completed: false, note: "Quotation QT-9203 drafted" },
      { stage: "Negotiation", date: "Pending", completed: false },
      { stage: "PO Expected", date: "22 Dec 2024", completed: false },
    ],
    createdAt: "2024-11-20",
    updatedAt: "2024-12-12",
  },
  {
    _id: "op-2",
    opportunityId: "OP-1024",
    leadId: "lead-1",
    customerId: "cust-2",
    customerName: "Senthil Nathan",
    companyName: "Apex Tooling Solutions",
    phone: "+91 98433 87123",
    email: "senthil@apextooling.in",
    franchiseId: "FR-CBE",
    franchiseName: "Coimbatore Franchise",
    stage: "Qualified",
    expectedValue: 1250000,
    product: "ARG-CL-200 Slant Bed Lathe",
    requirementsNotes: "Looking to replace legacy conventional lathe with CNC high precision lathe for tool holders.",
    timeline: [
      { stage: "New Lead", date: "05 Dec 2024", completed: true, note: "Met at INTEC" },
      { stage: "Qualified", date: "10 Dec 2024", completed: true, note: "Verified requirement for 8-station turret" },
      { stage: "Demo", date: "18 Dec 2024", completed: false, note: "Scheduled at Coimbatore Experience Center" },
    ],
    createdAt: "2024-12-05",
    updatedAt: "2024-12-10",
  },
];

export const MOCK_QUOTATIONS: Quotation[] = [
  {
    _id: "qt-1",
    quoteId: "QT-9203",
    opportunityId: "OP-1023",
    customerId: "cust-1",
    customerName: "Mr. M. Karthik",
    companyName: "Sri Venkatesh Industries",
    franchiseId: "FR-CBE",
    franchiseName: "Coimbatore Franchise",
    version: 1,
    items: [
      {
        sku: "ARG-VMC-700",
        name: "ARGUS VMC-700 3-Axis Vertical Machining Center",
        listPrice: 1850000,
        minSellingPrice: 1650000,
        maxDiscountPercent: 10,
        appliedDiscountPercent: 8,
        unitPrice: 1702000,
        quantity: 1,
        gstPercent: 18,
        installationCharge: 45000,
        total: 2053360,
      },
      {
        sku: "ARG-ACC-4AXIS",
        name: "4th Axis Rotary Table (200mm Dia)",
        listPrice: 280000,
        minSellingPrice: 250000,
        maxDiscountPercent: 10,
        appliedDiscountPercent: 5,
        unitPrice: 266000,
        quantity: 1,
        gstPercent: 18,
        installationCharge: 10000,
        total: 323880,
      },
    ],
    subtotal: 1968000,
    totalDiscount: 162000,
    taxAmount: 354240,
    installationTotal: 55000,
    grandTotal: 2377240,
    status: "Approved",
    requiresSpecialApproval: false,
    auditLogs: [
      {
        timestamp: "2024-12-12 11:30",
        user: "Karthik M (Franchise Sales)",
        action: "Quotation Generated",
        details: "Version 1 created within allowed discount limit (8% applied, max 10%).",
      },
      {
        timestamp: "2024-12-12 11:45",
        user: "Sundaramurthy K (Franchise Admin)",
        action: "Internal Approved",
        details: "Checked commercial terms and dispatched to customer.",
      },
    ],
    validUntil: "2025-01-12",
    createdAt: "2024-12-12",
  },
  {
    _id: "qt-2",
    quoteId: "QT-9204",
    opportunityId: "OP-1024",
    customerId: "cust-2",
    customerName: "Senthil Nathan",
    companyName: "Apex Tooling Solutions",
    franchiseId: "FR-CBE",
    franchiseName: "Coimbatore Franchise",
    version: 1,
    items: [
      {
        sku: "ARG-CL-200",
        name: "ARGUS CNC Lathe CL-200 Slant Bed",
        listPrice: 1250000,
        minSellingPrice: 1125000,
        maxDiscountPercent: 10,
        appliedDiscountPercent: 15, // EXCEEDS 10%!
        unitPrice: 1062500, // Below min selling price!
        quantity: 1,
        gstPercent: 18,
        installationCharge: 35000,
        total: 1288750,
      },
    ],
    subtotal: 1062500,
    totalDiscount: 187500,
    taxAmount: 191250,
    installationTotal: 35000,
    grandTotal: 1288750,
    status: "Pending_Approval",
    requiresSpecialApproval: true,
    approvalReason: "Competitor ACE Micromatic offered ₹10.8L. Client insists on 15% discount to seal deal before financial year end.",
    auditLogs: [
      {
        timestamp: "2024-12-14 14:10",
        user: "Karthik M (Franchise Sales)",
        action: "Special Price Approval Requested",
        details: "Applied 15% discount exceeds master policy of 10%. Submitted to Head Office for authorization.",
      },
    ],
    validUntil: "2024-12-31",
    createdAt: "2024-12-14",
  },
];

export const MOCK_ORDERS: SalesOrder[] = [
  {
    _id: "so-1",
    orderId: "SO-1023",
    quoteId: "QT-9188",
    opportunityId: "OP-980",
    customerId: "cust-1",
    customerName: "Mr. M. Karthik",
    companyName: "Sri Venkatesh Industries",
    franchiseId: "FR-CBE",
    franchiseName: "Coimbatore Franchise",
    poNumber: "PO-SVI-2024-884",
    poDate: "2024-11-28",
    orderValue: 2150000,
    orderStatus: "Dispatch",
    paymentSchedule: [
      {
        milestoneName: "Advance",
        percentage: 30,
        amount: 645000,
        dueDate: "2024-11-30",
        receivedAmount: 645000,
        receivedDate: "2024-11-29",
        referenceNumber: "UTR-HDFC-991823",
        status: "Received",
      },
      {
        milestoneName: "Before Dispatch",
        percentage: 60,
        amount: 1290000,
        dueDate: "2024-12-10",
        receivedAmount: 1290000,
        receivedDate: "2024-12-09",
        referenceNumber: "UTR-HDFC-994512",
        status: "Received",
      },
      {
        milestoneName: "Post Installation",
        percentage: 10,
        amount: 215000,
        dueDate: "2024-12-25",
        receivedAmount: 0,
        status: "Pending",
      },
    ],
    materialDispatchedDate: "2024-12-11",
    createdAt: "2024-11-28",
  },
];

export const MOCK_INSTALLATIONS: Installation[] = [
  {
    _id: "ins-1",
    installationId: "INS-1023",
    orderId: "SO-1023",
    customerId: "cust-1",
    customerName: "Mr. M. Karthik",
    companyName: "Sri Venkatesh Industries",
    franchiseId: "FR-CBE",
    machineSerial: "ARG-VMC-700-04122024",
    productName: "ARGUS VMC-700 3-Axis Vertical Machining Center",
    assignedEngineerId: "usr-cbe-eng",
    assignedEngineerName: "Ramesh Kumar",
    scheduledDate: "2024-12-15",
    checklist: {
      materialDelivered: true,
      preInstallCheck: true,
      machineInstalled: true,
      trainingCompleted: false,
      customerSignOff: false,
    },
    photos: [
      "https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?w=500&auto=format&fit=crop&q=60",
      "https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=500&auto=format&fit=crop&q=60",
    ],
    trainingDetails: {
      traineesCount: 3,
      operatorsTrained: ["P. Murugesan (Senior Operator)", "K. Loganathan (Junior Operator)"],
      topicsCovered: ["G-code fundamentals", "Tool length offset measurement", "Emergency shutdown procedures"],
    },
    status: "In Progress",
  },
];

export const MOCK_SUPPORT_TICKETS: SupportTicket[] = [
  {
    _id: "tk-1",
    ticketId: "TK-1056",
    customerId: "cust-1",
    customerName: "Mr. M. Karthik",
    companyName: "Sri Venkatesh Industries",
    franchiseId: "FR-CBE",
    machineSerial: "ARG-VMC-700-0382023",
    productName: "ARGUS VMC-700 (Spindle Unit)",
    category: "Breakdown",
    priority: "Critical",
    slaDeadline: new Date(Date.now() + 4 * 3600000).toISOString(),
    slaHoursTotal: 4,
    slaBreached: false,
    assignedEngineerId: "usr-cbe-eng",
    assignedEngineerName: "Ramesh Kumar",
    status: "In Progress",
    issueDescription: "Spindle drive alarm code E-04 (Over-torque during heavy roughing pass in D2 steel). Machine halted production.",
    comments: [
      {
        id: "c-1",
        authorName: "Mr. M. Karthik",
        role: "Customer MD",
        timestamp: "2024-12-14 09:15",
        message: "Machine stopped mid-cycle. Urgent attention requested as automotive batch delivery is due tomorrow.",
      },
      {
        id: "c-2",
        authorName: "Ramesh Kumar",
        role: "Service Engineer",
        timestamp: "2024-12-14 10:00",
        message: "Reached site at 09:50. Inspecting spindle servo drive cooling fan and IGBT module. Testing encoder feedback.",
      },
    ],
    createdAt: "2024-12-14 09:15",
  },
  {
    _id: "tk-2",
    ticketId: "TK-1057",
    customerId: "cust-2",
    customerName: "Mr. R. Kavitha Kumar",
    companyName: "Kavitha Precision Engineering",
    franchiseId: "FR-CBE",
    machineSerial: "ARG-CL-200-0112023",
    productName: "ARGUS CNC Lathe CL-200",
    category: "Calibration",
    priority: "Medium",
    slaDeadline: new Date(Date.now() + 24 * 3600000).toISOString(),
    slaHoursTotal: 24,
    slaBreached: false,
    assignedEngineerId: "usr-cbe-eng",
    assignedEngineerName: "Ramesh Kumar",
    status: "Open",
    issueDescription: "Z-axis backlash deviation of 0.015mm noticed during fine thread turning.",
    comments: [],
    createdAt: "2024-12-13 16:30",
  },
];

export const MOCK_RENEWALS: Renewal[] = [
  {
    _id: "rn-1",
    renewalId: "RN-402",
    customerId: "cust-1",
    customerName: "Mr. M. Karthik",
    companyName: "Sri Venkatesh Industries",
    franchiseId: "FR-CBE",
    franchiseName: "Coimbatore Franchise",
    machineSerial: "ARG-VMC-700-0382023",
    productOrModule: "VMC-700 Comprehensive AMC & Spindle Cover",
    expiryDate: "2025-01-15",
    daysRemaining: 24,
    contractValue: 72000,
    status: "Notice_30d",
    remindersSent: [
      { type: "60d", sentAt: "2024-11-15", channel: "Email" },
      { type: "30d", sentAt: "2024-12-15", channel: "WhatsApp" },
    ],
  },
  {
    _id: "rn-2",
    renewalId: "RN-403",
    customerId: "cust-2",
    customerName: "Mr. R. Kavitha Kumar",
    companyName: "Kavitha Precision Engineering",
    franchiseId: "FR-CBE",
    franchiseName: "Coimbatore Franchise",
    machineSerial: "ARG-SOFT-CAM-102",
    productOrModule: "ArgusCAM Pro Multi-Axis Software Subscription",
    expiryDate: "2024-12-28",
    daysRemaining: 6,
    contractValue: 25000,
    status: "Notice_7d",
    remindersSent: [
      { type: "60d", sentAt: "2024-10-28", channel: "Email" },
      { type: "30d", sentAt: "2024-11-28", channel: "Email" },
      { type: "15d", sentAt: "2024-12-13", channel: "WhatsApp" },
      { type: "7d", sentAt: "2024-12-21", channel: "In-App" },
    ],
  },
];

export const MOCK_COMMISSIONS: CommissionRecord[] = [
  {
    _id: "comm-1",
    commissionId: "COMM-7801",
    franchiseId: "FR-CBE",
    franchiseName: "Coimbatore Franchise",
    orderId: "SO-1023",
    customerName: "Sri Venkatesh Industries",
    eligibleRevenue: 1935000, // payments received (advance + dispatch)
    commissionRate: 8, // 8% slab
    calculatedAmount: 154800,
    status: "Payable",
    createdAt: "2024-12-10",
  },
  {
    _id: "comm-2",
    commissionId: "COMM-7789",
    franchiseId: "FR-CBE",
    franchiseName: "Coimbatore Franchise",
    orderId: "SO-0994",
    customerName: "Kavitha Precision Engineering",
    eligibleRevenue: 1250000,
    commissionRate: 8,
    calculatedAmount: 100000,
    status: "Paid",
    paymentReference: "NEFT-ARGUS-99120",
    paidDate: "2024-11-30",
    createdAt: "2024-11-20",
  },
];

export const MOCK_TERRITORIES: TerritoryMapping[] = [
  {
    _id: "ter-1",
    country: "India",
    state: "Tamil Nadu",
    district: "Coimbatore",
    pincodeRange: ["641001", "641002", "641004", "641014", "641018", "641021", "641035"],
    assignedFranchiseId: "FR-CBE",
    assignedFranchiseName: "Coimbatore Franchise",
    isProtected: true,
  },
  {
    _id: "ter-2",
    country: "India",
    state: "Tamil Nadu",
    district: "Tiruppur",
    pincodeRange: ["641601", "641602", "641603"],
    assignedFranchiseId: "FR-CBE",
    assignedFranchiseName: "Coimbatore Franchise",
    isProtected: false,
  },
  {
    _id: "ter-3",
    country: "India",
    state: "Tamil Nadu",
    district: "Chennai",
    pincodeRange: ["600001", "600028", "600032", "600058", "600096"],
    assignedFranchiseId: "FR-CHE",
    assignedFranchiseName: "Chennai Franchise",
    isProtected: true,
  },
  {
    _id: "ter-4",
    country: "India",
    state: "Karnataka",
    district: "Bangalore Urban",
    pincodeRange: ["560001", "560058", "560068", "560100"],
    assignedFranchiseId: "FR-BLR",
    assignedFranchiseName: "Bangalore Franchise",
    isProtected: true,
  },
];
